---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guonan.
--- DateTime: 2026/1/3 12:19
---

function test2()
    
end

function test5()

end

function test7()

end

function test7()
    print("11112")
end